# Generated by Django 5.0.6 on 2024-06-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MentalHealthData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_point", models.CharField(max_length=100)),
                ("value", models.IntegerField()),
            ],
        ),
    ]
